### ISSUE TITLE
Missing outputs when running pepita with "FileNotFoundError"

### ISSUE THREAD

**Issue by mengqinqqq** [ma-lab-cgidr/zebrafish-quantification#2]
I’m running pepita and successfully obtained the output values. However, I’m encountering a problem where some other outputs are not appearing, and I am receiving a "FileNotFoundError".

**Comment by ethanbustad** [comment]
More info on the error message:

![image](https://github.com/user-attachments/assets/0dc439da-c444-44bd-ae66-46f87478f0b9)
